# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: Medha Karri
title: Sr. Product Manager - Technical, Amazon Simple Email Service
email: medhachaitanya@outlook.com
# email_title: Email (Email title override)
# phone: Your phone number (optional)
# phone_title: Phone (Phone title override)
# website: Your website (eg. https://google.com)(optional)
# website_title: Web (Website title override)

# Dark Mode (true/false/never)
darkmode: false

# Social links
#twitter_username: jekyllrb
github_username:  medhachaitanya
#stackoverflow_username: "00000001"
#dribbble_username: jekyll
#facebook_username: jekyll
#flickr_username: jekyll
#instagram_username: jekyll
linkedin_username: medhakarri
#xing_username: jekyll
#pinterest_username: jekyll
#youtube_username: jekyll
#googleplus_username: +jekyll
#orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: Link name
#   icon: Font Awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/profilepic.jpg
about_content:  # this will include new lines to allow paragraphs
  Hi, I go by Medha. <br /><br />I'm a technology enthusiast having varied experience in product management and software development. I like solving tech problems, talk to customers and build products that empower people, work better and make the world a better place to live.
  <br />
  <br />
  I believe there's certainly yet more to learn, yet more problems to face and solve.
  <br />
  <br />  
  KEY SKILLS
  <br />
  <b style='color:green'>Technical Product Management | Software Development | Adaptability | User Experience | Leadership | Communications & Training | Problem Solving | Risk Mitigation | Escalation Management | Data Analysis | Process Improvement | Project Management | Systems Design | Revenue Strategy | Product Roadmap | Tableau | Quick Sight</b>
  <br />    
  <br />  
  Other Technical Skills
  <br />
  <b style='color:green'>AWS, Microsoft Azure, General Cloud Computing, Cloud Systems & Infrastructure, ServiceNow Development, Web development on ReactJS, OPENUI5, SAPUI5, General DevOps, Docker, JavaScript, SAP FIORI, C#, Apache Cordova, Windows App Development (UWP)</b>


content:
  - title: Notable Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Pure Battery Analytics
        link: https://apps.microsoft.com/detail/9nblggh4x4k3?hl=en-US&gl=US
        link_text: Link to the app
        additional_links:
          - title: GitHub Repository
            icon: fab fa-github
            url: https://github.com/medhachaitanya/Pure-Battery-Analytics
        quote: >
          Try it, love it!
        description: | # this will include new lines to allow paragraphs
          <p style="color:green">🚀 The **highest-rated** battery analytics app on the Microsoft Store, with **100K+ users globally** and an impressive **4.7/5 average rating**.</p>
          <br/>
          **Key Features:**  
          - Provides **advanced battery analytics**, including **battery life estimates, power settings, system insights, and real-time optimizations**.  
          - Runs **seamlessly in the background**, ensuring minimal impact on system performance.  
          - Designed for **Windows 10/11**, leveraging **Windows Universal SDK, C#, SQLite, XAML, and Telerik UI libraries**.  

    
  
  - title: Previous Experience
    layout: list
    content:
      - layout: right
        title: ServiceNow
        sub_title: Sr. Software Engineer + Intern
        caption: Jan 2021 - Sep 2022 (Full-Time), May 2020 - Aug 2020 (Internship)
        link: www.servicenow.com
        quote: >
          Making work, work better for everyone
        description: | # this will include new lines to allow paragraphs
          During my internship, I proposed and developed an MVP tool for Cloud Cost Monitoring & Optimization, which evolved into a full-fledged product offering — <a href="https://www.servicenow.com/products/it-operations-management/what-is-cloud-center-of-excellence.html" target="_blank"><b>Cloud Center of Excellence (CCOE)</b></a>.
          <br/>
          <br/>
          As a full-time engineer, I played a key role in defining product features, shaping the roadmap, and contributing to overall strategy. While my primary focus was on product management, I was also actively involved in **systems design** and **software development** components.
          <br/>
          <br/>
          Additionally, I collaborated with **cross-functional and remote teams**, coordinated efforts across multiple departments, and regularly communicated product updates to senior management.
          <br/>
          
      - layout: right
        title: Wright State University
        sub_title: Graduate Research Assistant (U.S. Air Force Research Laboratory Project) 
        caption: 2019 - 2021
        link: www.wright.edu/
        description: | # this will include new lines to allow paragraphs
          Led the design and development of a **data mining and analytics platform** for a research initiative for U.S. Department of the Air Force.  
          <br/>
          <br/>
          The platform enabled comprehensive **trend analysis** in key fields of study, supporting strategic research and innovation efforts for U.S. Air Force Science and Technology (AFRL) Strategy.  
          <br/>
          <br/>
          Additional details available upon request.
          
      - layout: right
        title: Deloitte
        sub_title: Business Analyst
        caption: 2018 - 2019
        link: www.deloitte.com
        quote: >
          Helping clients and people excel
        description: | # this will include new lines to allow paragraphs
          Contributed to the **integration design team** for **Workday implementations**, focusing on seamless system integrations and business process automation.  
          <br/>
          <br/>
          Key responsibilities included **team management, strategic planning, and business analysis**, working closely with clients to translate their requirements into effective solutions.  
          <br/>
          <br/>
          **Primary skills**: Workday HCM, Workday Integrations, Business Analysis, Client Requirement Analysis, XML, XSLT, SOAP, Azure, JavaScript.  
          <br/>
          <br/>
          <p style="color:green"><b>Successfully contributed to two major Workday implementations for enterprise clients.</b></p>



      - layout: right
        title: Accenture
        sub_title: Senior Application Developer
        caption: 2015 - 2018
        link: www.accenture.com
        quote: >
          High Performance. Delivered.
        description: | # this will include new lines to allow paragraphs
          Part of the development team for SAPUI5 and Fiori. 
          My job responsibilities include being a good team player, write code and bring innovations. <br/>
          <p style='color:green'>Recipient of multiple awards for client innovation and individual performance at org level.</p>
          
      - layout: right
        title: DailyPlus
        sub_title: Co-Founder & CEO
        caption: 2013 - 2017
        link: https://dailyplus.app/
        quote: >
          Empowering dairy-based small businesses with seamless invoicing and billing solutions
        description: | # this will include new lines to allow paragraphs
          Led and managed a **team of 18** in building and scaling DailyPlus, a digital invoicing and billing solution tailored for dairy-based small businesses.  
          <br/>
          <br/>
          Spearheaded **product design, strategy, and execution**, driving innovation and market adoption.  
          <br/>
          <br/>
          **Incubation & Recognition:**  
          - Part of the **T-Hub incubator (2015-2017), Hyderabad, India**.  
          - Part of **NASSCOM 10,000 Startups (2015-2018), Hyderabad, India**.  
          <br/>
          <br/>
          **Achievements:**  
          <p style="color:green">🏆 Winner of **Kotak Mahindra Co-Create Innovation Hackathon**, hosted by one of India's top banks (<a href="https://bit.ly/3EzTvfe" target="_blank">Learn more</a>).</p>
          <p style="color:green">🚀 Selected among the **top 15 startups** for mentorship and incubation at the **Indian School of Business (Jumpstart Program), Hyderabad**.</p>
          <p style="color:green">📈 Recognized among the **top 150 fastest-growing startups** in 2016 by **Economic Times Power of Ideas, IIM-Calcutta**.</p>
          <!-- <p style="color:green">Startup acquired by a private entity.</p> -->
      
      - layout: right
        title: Microsoft
        sub_title: Microsoft Student Partner
        caption: 2012 - 2013
        link: www.microsoft.com
        quote: >
          Your potential, our passion
        description: | # this will include new lines to allow paragraphs
          Contributed to the **Windows Apps development team** for **Windows 8 and 8.1**, assisting in building and optimizing applications for the platform.  
          <br/>
          <br/>
          **Achievements:**  
          <p style="color:green">🏆 **Winner of Windows 8 Apps Hackathon (Wowzapp 2012)**, a global coding competition hosted by Microsoft.</p>  
          <p style="color:green">🚀 **Recipient of the Top Community Contributor Award** for outstanding contributions to **Microsoft Azure**.</p>


  - title: Education
    layout: list
    content:
      - layout: top-right
        title: Wright State University, USA
        sub_title: Masters in Computer Science
        caption: <p style='color:green'>3.6/4 CGPA, 2019 - 2021</p>
      - layout: top-right
        title: Lakireddy Balireddy College of Engineering, India
        sub_title: Bachelors in Computer Science
        caption: <p style='color:green'>3.3/4 CGPA, 2010 - 2014</p>
        # quote: >
          # We are Raiders!
        #description: | # this will include new lines to allow paragraphs
         # Description of qualification
  
  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Technology enthusiast, experimentalist, friendly, altruistic, hard-working and ambitious individual who loves to contribute & learn.
      Please refer to my LinkedIn profile to know more details on my skills, accomplishments and others. 
      

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
